{{- if .Values.ingress.enabled -}}
{{- $fullName := .Release.Name | quote -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ required "A valid .Values.namespace entry is required" .Values.namespace }}
  labels:
    {{- include "helm-k8s-php-deployer.labels" . | nindent 4 }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ default .path "/" | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
  {{- end }}
{{- end }}