apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ required "A valid .Values.namespace entry is required" .Values.namespace }}
  labels:
    {{- include "helm-k8s-php-deployer.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
      {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm-k8s-php-deployer.selectorLabels" . | nindent 4 }}